// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmQeUJazCIlqQWQqIYrvec_P7-2jJ6k3A',
    appId: '1:992779099398:web:fa9426218508d9059b9287',
    messagingSenderId: '992779099398',
    projectId: 'shurokkha-agent',
    authDomain: 'shurokkha-agent.firebaseapp.com',
    storageBucket: 'shurokkha-agent.appspot.com',
    measurementId: 'G-JG34WFPHZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIGLYCCnD4mN5DfVeEbkmCpOHsBCts-eU',
    appId: '1:992779099398:android:56d0f63c1464326e9b9287',
    messagingSenderId: '992779099398',
    projectId: 'shurokkha-agent',
    storageBucket: 'shurokkha-agent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcpJyH8zt-5wMC2qdXR4QhdkehqgSdsYE',
    appId: '1:992779099398:ios:99dd762e2a6da7389b9287',
    messagingSenderId: '992779099398',
    projectId: 'shurokkha-agent',
    storageBucket: 'shurokkha-agent.appspot.com',
    androidClientId: '992779099398-gdvp4sbafn2d3vimrls7el1tv0u0tigl.apps.googleusercontent.com',
    iosClientId: '992779099398-be6k5fllq99bs9g3u3ptavm9abpljcip.apps.googleusercontent.com',
    iosBundleId: 'com.example.surokkha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcpJyH8zt-5wMC2qdXR4QhdkehqgSdsYE',
    appId: '1:992779099398:ios:99dd762e2a6da7389b9287',
    messagingSenderId: '992779099398',
    projectId: 'shurokkha-agent',
    storageBucket: 'shurokkha-agent.appspot.com',
    androidClientId: '992779099398-gdvp4sbafn2d3vimrls7el1tv0u0tigl.apps.googleusercontent.com',
    iosClientId: '992779099398-be6k5fllq99bs9g3u3ptavm9abpljcip.apps.googleusercontent.com',
    iosBundleId: 'com.example.surokkha',
  );
}
